AWSTemplateFormatVersion: "2010-09-09"

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "BucketName"
        Parameters:
          - BucketName
      - Label:
          default: "WAFWebACLMetricName"
        Parameters:
          - WAFWebACLMetricName

Parameters:
  BucketName:
    Type: String
  WAFWebACLMetricName:
    Type: String
    MinLength: 1
    MaxLength: 128
    AllowedPattern: "[a-zA-Z0-9]*"

Resources:
  WAFWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: "Maintenance-WebACL"
      Scope: "CLOUDFRONT"
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: !Ref WAFWebACLMetricName
        SampledRequestsEnabled: true
      DefaultAction:
        Block: {}

  BucketForTest:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      
  BucketPolicyForTest:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketForTest
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudfrontForTestOriginAccessIdentity}
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${BucketForTest}/*

  CloudfrontForTestOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub access-identity-${BucketName}.s3.amazonaws.com

  CloudfrontForTest:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: "for maintenance page test"
        PriceClass: PriceClass_200
        DefaultRootObject: index.html
        Origins:
          - DomainName: !GetAtt BucketForTest.DomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudfrontForTestOriginAccessIdentity}"
        IPV6Enabled: true
        HttpVersion: http2
        DefaultCacheBehavior:
          AllowedMethods:
            - HEAD
            - GET
          CachedMethods:
            - HEAD
            - GET
          Compress: false
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 0
          ForwardedValues:
            QueryString: false
            Headers:
              - Origin
              - Access-Control-Request-Headers
              - Access-Control-Request-Method
          SmoothStreaming: false
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
        # カスタムエラーレスポンス
        CustomErrorResponses:
        - ErrorCode: '403'
          ResponsePagePath: "/maintenance.html"
          ResponseCode: '503'
        # WAFのアタッチ
        WebACLId: !Ref WAFWebACL